name: End-to-end tests
on: deployment

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: mikefrancis/vercel-cypress@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          repo: interviewor
